[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/survey"
  to = "/survey.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
